CONFIG_ZMK_USB_LOGGING=n

# Mouse keys
CONFIG_ZMK_MOUSE=y
CONFIG_ZMK_MOUSE_DEFAULT_MOVE_VAL=1500
CONFIG_ZMK_MOUSE_DEFAULT_SCRL_VAL=20

# Power saving
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_TIMEOUT=60000
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000

# Bluetooth
CONFIG_ZMK_BT_MAX_CONN=5
CONFIG_ZMK_BT_MAX_PAIRED=5

# Combos
CONFIG_ZMK_COMBO_TERM_MS=40
